tc-django-master/computacao/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'computacao'

urlpatterns = [
                  path('', views.index, name='index'),
                  path('index/', views.index, name='index'),
                  path('automatos/', views.automatos, name='automatos'),
                  path('novo_automato/', views.novo_automato, name='novo_automato'),
                  path('edita_automato/<int:automato_id>/', views.edita_automato, name='edita_automato'),
                  path('apaga_automato/<int:automato_id>/', views.apaga_automato, name='apaga_automato'),
                  path('<int:automato_id>/automato/', views.automato, name='automato'),
                  
                  path('maquinas/',views.maquinas,name='maquinas'),
                  path('novamaquina/', views.novamaquina, name='novamaquina'),
                  path('editamaquina/<int:maquina_id>/', views.editamaquina, name='editamaquina'),
                  path('apagamaquina/<int:maquina_id>/', views.apagamaquina, name='apagamaquina'),
                  path('<int:maquina_id>/maquina/', views.maquina, name='maquina'), 

                  path('expressoes/',views.expressoes,name='expressoes'),
                  path('novaexpressao/', views.novaexpressao, name='novaexpressao'),
                  path('editaexpressao/<int:expressao_id>/', views.editaexpressao, name='editaexpressao'),
                  path('apagaexpressao/<int:expressao_id>/', views.apagaexpressao, name='apagaexpressao'),
                  path('<int:expressao_id>/expressao/', views.expressao, name='expressao')                                 
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tc-django-master/tc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('computacao.urls'), name='computacao'),
]

tc-django-master/computacao/forms.py
from django import forms
from django.forms import ModelForm
from .models import Automato, Expressao,Maquina


class SequenciaForm(forms.Form):
    sequencia = forms.CharField(label='',
                                widget=forms.TextInput(attrs={
                                    'placeholder': 'insira uma sequência binária',
                                    'size': '25'
                                }))


class AutomatoForm(ModelForm):
    class Meta:
        model = Automato
        fields = '__all__'   # pode-se especificar lista dos campos q queremos. podemos querer tudo excluindo alguns
        exclude = ['diagrama']

        # inserção de classes CSS para formatação de cada campo do formulário
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'descricao': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'AFD que aceita sequências ...'}),
            'alfabeto': forms.TextInput(attrs={'class': 'form-control'}),
            'estados': forms.TextInput(attrs={'class': 'form-control'}),
            'estadoInicial': forms.TextInput(attrs={'class': 'form-control'}),
            'estadosDeAceitacao': forms.TextInput(attrs={'class': 'form-control'}),
            'dicionarioTransicao': forms.TextInput(attrs={'class': 'form-control'}),
        }

        labels = {
            'nome': 'Nome do autómato',
            'descricao': 'Descrição',
            'alfabeto': 'Alfabeto de símbolos',
            'estados': 'Estados',
            'estadoInicial': 'Estado inicial',
            'estadosDeAceitacao': 'Estado de aceitação',
            'dicionarioTransicao': 'Transições'
        }

        placeholders = {
            'nome': 'Nome do autómato',
            'descricao': 'Descrição',
            'alfabeto': 'Alfabeto de símbolos',
            'estados': 'Estados',
            'estadoInicial': 'Estado inicial',
            'estadosDeAceitacao': 'Estado de aceitação',
            'dicionarioTransicao': 'Transições'
        }

        help_texts = {
            'nome': 'Atribua um nome, com no máximo 3 palavras,  que identifique o AFD',
            'descricao': 'Descreva o tipo de sequências que o autómato reconhece',
            'alfabeto': 'Insira os simbolos do alfabeto separados por espaços (e.g. "0 1")',
            'estados': 'Insira os nomes dos estados separados por espaços (e.g. "A B")',
            'estadosDeAceitacao': 'Insira os estados separados por espaços (e.g. "A B")',
            'dicionarioTransicao': 'Insira as transicoes estadoInicial-simbolo-estadoSeguinte (e.g. "A-0-B A-1-A")'
        }

class MaquinaForm(ModelForm):
    class Meta:
        model = Maquina
        fields = '__all__'   # pode-se especificar lista dos campos q queremos. podemos querer tudo excluindo alguns
        exclude = ['diagrama']

        # inserção de classes CSS para formatação de cada campo do formulário
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'descricao': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Maquina que aceita sequências ...'}),
            'alfabeto': forms.TextInput(attrs={'class': 'form-control'}),
            'estados': forms.TextInput(attrs={'class': 'form-control'}),
            'estadoInicial': forms.TextInput(attrs={'class': 'form-control'}),
            'estadosDeAceitacao': forms.TextInput(attrs={'class': 'form-control'}),
            'dicionarioTransicao': forms.TextInput(attrs={'class': 'form-control'}),
        }

        labels = {
            'nome': 'Nome da máquina',
            'descricao': 'Descrição',
            'alfabeto': 'Alfabeto de símbolos',
            'estados': 'Estados',
            'estadoInicial': 'Estado inicial',
            'estadosDeAceitacao': 'Estado de aceitação',
            'dicionarioTransicao': 'Transições'
        }

        placeholders = {
            'nome': 'Nome da máquina',
            'descricao': 'Descrição',
            'alfabeto': 'Alfabeto de símbolos',
            'estados': 'Estados',
            'estadoInicial': 'Estado inicial',
            'estadosDeAceitacao': 'Estado de aceitação',
            'dicionarioTransicao': 'Transições'
        }

        help_texts = {
            'nome': 'Atribua um nome, com no máximo 3 palavras,  que identifique a Máquina',
            'descricao': 'Descreva o tipo de sequências que a máquina reconhece',
            'alfabeto': 'Insira os simbolos do alfabeto separados por espaços (e.g. "0 1 *,sempre nesta ordem")',
            'estados': 'Insira os nomes dos estados separados por espaços (e.g. "A B")',
            'estadosDeAceitacao': 'Insira os estados separados por espaços (e.g. "A B")',
            'dicionarioTransicao': 'Insira as transicoes estadoInicial-simbolo-estadoSeguinte (e.g. "A-01L-B A-10R-A B-**L-A")'
        }

class ExpressaoForm(ModelForm):
    class Meta:
        model = Expressao
        fields = '__all__'  
        exclude = ['diagrama']

        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'descricao': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Regex que aceita sequências ...'}),
            'regex': forms.TextInput(attrs={'class': 'form-control'})
 
        }

        labels = {
            'nome': 'Nome da expressão',
            'descricao': 'Descrição',
            'regex': 'regex da expressao'
        }

        placeholders = {
            'nome': 'Nome da máquina',
            'descricao': 'Descrição',
            'regex': 'regex da expressao'

        }

        help_texts = {
            'nome': 'Atribua um nome,  que identifique a Expressao',
            'descricao': 'Descreva o tipo de sequências o regex reconhece',
            'regex': 'Insira os simbolos do regex (e.g. "^[0-9][4][-/s][0-9][3]$")'

        }

tc-django-master/computacao/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Automato, Expressao, Maquina
from .forms import ExpressaoForm, SequenciaForm, AutomatoForm, MaquinaForm


def index(request):
    return render(request, 'computacao/index.html')



def automato(request, automato_id):

    sequencia = None
    resultado = None

    form = SequenciaForm(request.POST or None)
    if form.is_valid():
        sequencia = form.cleaned_data['sequencia']
        resultado = Automato.objects.get(id=automato_id).valida_sequencia(sequencia)

    context = {
        'automato': Automato.objects.get(id=automato_id),
        'sequencia': sequencia,
        'resultado': resultado,
        'form': form,
    }
    return render(request, 'computacao/automato.html', context)


def automatos(request):

    context = {'automatos': Automato.objects.all()}
    return render(request, 'computacao/automatos.html', context)


def novo_automato(request):

    form = AutomatoForm(request.POST or None)
    if form.is_valid():
        new_automata = form.save()
        new_automata.desenha_diagrama()
        new_automata.save()
        return HttpResponseRedirect(reverse('computacao:automatos'))

    context = {'form': form}

    return render(request, 'computacao/novo_automato.html', context)


def edita_automato(request, automato_id):
    """if request.POST == 'POST':
        form = AutomatoForm(request.POST)
        form.save()"""

    instance = Automato.objects.get(id=automato_id)
    form = AutomatoForm(request.POST or None, instance=instance)
    if form.is_valid():
        a = form.save()
        a.desenha_diagrama()
        a.save()
        return HttpResponseRedirect(reverse('computacao:automatos'))


    context = {'form': form, 'automato_id':automato_id}
    return render(request, 'computacao/edita_automato.html', context)

def apaga_automato(request, automato_id):
    Automato.objects.filter(id=automato_id).delete()
    context = {'automatos': Automato.objects.all()}
    return render(request, 'computacao/automatos.html', context)

def maquina(request, maquina_id):

    sequencia = None
    resultado = None

    form = SequenciaForm(request.POST or None)
    if form.is_valid():
        sequencia = form.cleaned_data['sequencia']
        resultado = Maquina.objects.get(id=maquina_id).valida_sequencia(sequencia)

    context = {
        'maquina': Maquina.objects.get(id=maquina_id),
        'sequencia': sequencia,
        'resultado': resultado,
        'form': form,
    }
    return render(request, 'computacao/maquina.html', context)


def maquinas(request):

    context = {'maquinas': Maquina.objects.all()}
    return render(request, 'computacao/maquinas.html', context)

def novamaquina(request):

    form = MaquinaForm(request.POST or None)
    if form.is_valid():
        nova_maquina = form.save()
        nova_maquina.desenha_diagrama()
        nova_maquina.save()
        return HttpResponseRedirect(reverse('computacao:maquinas'))

    context = {'form': form}

    return render(request, 'computacao/novamaquina.html', context)

def editamaquina(request, maquina_id):

    instance = Maquina.objects.get(id=maquina_id)
    form = MaquinaForm(request.POST or None, instance=instance)
    if form.is_valid():
        a = form.save()
        a.desenha_diagrama()
        a.save()
        return HttpResponseRedirect(reverse('computacao:maquinas'))


    context = {'form': form, 'maquina_id':maquina_id}
    return render(request, 'computacao/editamaquina.html', context)

def apagamaquina(request, maquina_id):
    Maquina.objects.filter(id=maquina_id).delete()
    context = {'maquinas': Maquina.objects.all()}
    return render(request, 'computacao/maquinas.html', context)

def expressao(request, expressao_id):

    sequencia = None
    resultado = None

    form = SequenciaForm(request.POST or None)
    if form.is_valid():
        sequencia = form.cleaned_data['sequencia']
        resultado = Expressao.objects.get(id=expressao_id).valida_sequencia(sequencia)

    context = {
        'expressao': Expressao.objects.get(id=expressao_id),
        'sequencia': sequencia,
        'resultado': resultado,
        'form': form,
    }
    return render(request, 'computacao/expressao.html', context)


def expressoes(request):

    context = {'expressoes': Expressao.objects.all()}
    return render(request, 'computacao/expressoes.html', context)

def novaexpressao(request):

    form = ExpressaoForm(request.POST or None)
    if form.is_valid():
        nova_expressao = form.save()
        nova_expressao.save()
        return HttpResponseRedirect(reverse('computacao:expressoes'))

    context = {'form': form}

    return render(request, 'computacao/novaexpressao.html', context)

def editaexpressao(request, expressao_id):


    instance = Expressao.objects.get(id=expressao_id)
    form = ExpressaoForm(request.POST or None, instance=instance)
    if form.is_valid():
        a = form.save()
        a.save()
        return HttpResponseRedirect(reverse('computacao:expressoes'))


    context = {'form': form, 'expressao_id':expressao_id}
    return render(request, 'computacao/editaexpressao.html', context)

def apagaexpressao(request, expressao_id):
    Expressao.objects.filter(id=expressao_id).delete()
    context = {'expressoes': Expressao.objects.all()}
    return render(request, 'computacao/expressoes.html', context)

tc-django-master/computacao/templates/computacao/automato.html
{% extends 'computacao/layout.html' %}

{% block main %}


    <main class="col-sm-12">

        <h3>{{ automato.nome|title }}</h3>

        <p>{{ automato.descricao }}.</p>

        <table align="center">
            <tr align="left">
                <td>
                    <p> <b>Quíntuplo do autómato:</b></p>
                    <ul>
                    <li>Alfabeto: {{ automato.printAlfabeto }} </li>
                    <li>Estados: {{ automato.printEstados }}</li>
                    <li>Estado inicial: {{ automato.estadoInicial }}</li>
                    <li>Estados aceitação: {{ automato.printEstadosDeAceitacao }}</li>

                    <li>Tabela de transições:
                    <table align="center" rules="all" style="border-collapse: collapse">
                        {% for dTran in automato.dTransInTable %}
                            <tr>
                                {% for element in dTran %}
                                    {% if forloop.parentloop.first %}
                                        <th>{{ element }}</th>
                                    {% elif forloop.first %}
                                        <th>{{ element }}</th>
                                    {% else %}
                                        <td>{{ element }}</td>
                                    {% endif %}
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </table>
                    </ul>
                </li>
                </td>
                <td class="align-baseline">

                    {% load static %}
                    <img src="{% static automato.diagrama %}" alt="">
                    <p class="text-center">Diagrama de transições.</p>
                </td>
            </tr>
        </table>


        <br>
        <p><b>Validador:</b> Insira uma sequência e verifique se pertence à linguagem que o AFD reconhece: </p>
        <form action="{% url 'computacao:automato' automato.id %}" method="POST">
            {% csrf_token %}
           <b>{{ form }}</b>
            <input type="submit" value="validar" class="btn btn-success">
        </form>

        {% if resultado != None %}
            {% if resultado == True %}
                <p>A sequência <b>{{ sequencia }}</b> é aceite pelo autómato </p>
            {% else %}
                <p>A sequência <b>{{ sequencia }}</b> não é aceite pelo autómato </p>
            {% endif %}
        {% else %}
            <br><br>
        {% endif %}


    </main>

{% endblock %}


{% block aside %}
{% endblock %}

tc-django-master/computacao/templates/computacao/automatos.html
{% extends 'computacao/layout.html' %}

{% block main %}

    <main class="col-sm-12 text-center">

        <h3>Autómatos Finitos Determinísticos (AFD)</h3>
        <a href="{% url 'computacao:novo_automato' %}" class="btn btn-success btn-sm btn-block">
            Crie um AFD
        </a>
        <br>
        <p>Apresentam-se em baixo autómatos que foram criados.</p>

        <table align="center" class="table" style="max-width:900px">
            <tr>
                <th class="text-center">Diagrama de Estados</th>
                <th class="text-center">Descrição</th>
            </tr>
            {% load static %}
            {% for automato in automatos %}
                <tr class="text-left">
                    <td>
                        <a href="{% url 'computacao:automato' automato.id %}">
                            <img src="{% static automato.diagrama %}" alt="" width="80%">
                        </a>
                    </td>
                    <td style="vertical-align:bottom">
                        <p>{{ automato.descricao }}</p>
                        <p>
                            <a href="{% url 'computacao:automato' automato.id %}" class="btn btn-info  btn-sm">
                                Detalhes
                            </a>
                            <a href="{% url 'computacao:automato' automato.id %}" class="btn btn-success  btn-sm">
                                Validar Sequência
                            </a>
                            <a href="{% url 'computacao:edita_automato' automato.id %}" class="btn btn-warning  btn-sm">
                                Editar AFD
                            </a>
                            <a href="{% url 'computacao:apaga_automato' automato.id %}" class="btn btn-danger  btn-sm">
                                Apagar AFD
                            </a>
                        </p>

                    </td>

                </tr>
            {% endfor %}
        </table>

    </main>

{% endblock %}

{% block aside %}
{% endblock %}

tc-django-master/computacao/templates/computacao/edita_automato.html
{% extends 'computacao/layout.html' %}

{% block main %}
    <main class="col-sm-12">
        <h3>Autómato Finito Determinístico</h3>
        <p>Pode aqui especificar um novo autómato que ficará armazenado na base de dados, juntamente com o seu diagrama.
            O autómato será implementado e poderá ser usado.</p>

        <form class="form-group" action="{% url 'computacao:edita_automato' automato_id %}" method="POST">

            {% csrf_token %}

            {{ form.as_p }}

            <div class="text-right">
                <a href="{% url 'computacao:automatos' %}" role="button" class="btn btn-warning">Cancelar</a>
                <input type="submit" class="btn btn-success" value="submeter">
            </div>

        </form>

    </main>
{% endblock %}

tc-django-master/computacao/templates/computacao/editaexpressao.html
{% extends 'computacao/layout.html' %}

{% block main %}
    <main class="col-sm-12">
        <h3>Expressões Regulares</h3>
        <p>Pode aqui especificar uma nova expressão que ficará armazenada na base de dados.
            O regex será implementado e poderá ser usado.</p>

        <form class="form-group" action="{% url 'computacao:editaexpressao' expressao_id %}" method="POST">

            {% csrf_token %}

            {{ form.as_p }}

            <div class="text-right">
                <a href="{% url 'computacao:expressoes' %}" role="button" class="btn btn-warning">Cancelar</a>
                <input type="submit" class="btn btn-success" value="submeter">
            </div>

        </form>

    </main>
{% endblock %}

tc-django-master/computacao/templates/computacao/editamaquina.html
{% extends 'computacao/layout.html' %}

{% block main %}
    <main class="col-sm-12">
        <h3>Máquina Turing</h3>
        <p>Pode aqui especificar uma nova máquina que ficará armazenada na base de dados, juntamente com o seu diagrama.
            A máquina será implementada e poderá ser usada.</p>

        <form class="form-group" action="{% url 'computacao:editamaquina' maquina_id %}" method="POST">

            {% csrf_token %}

            {{ form.as_p }}

            <div class="text-right">
                <a href="{% url 'computacao:maquinas' %}" role="button" class="btn btn-warning">Cancelar</a>
                <input type="submit" class="btn btn-success" value="submeter">
            </div>

        </form>

    </main>
{% endblock %}

tc-django-master/computacao/templates/computacao/expressao.html
{% extends 'computacao/layout.html' %}

{% block main %}


    <main class="col-sm-12">

        <h3>{{ expressao.nome|title }}</h3>

        <p>{{ expressao.descricao }}.</p>

        <table align="center">
            <tr align="left">
                <td>
                    <p> <b>Regex da expressao:</b></p>

                    <li>Regex: {{ expressao.printRegex }} </li>


        <br>
        <p><b>Validador:</b> Insira uma sequência e verifique se pertence à linguagem que o regex reconhece: </p>
        <form action="{% url 'computacao:expressao' expressao.id %}" method="POST">
            {% csrf_token %}
           <b>{{ form }}</b>
            <input type="submit" value="validar" class="btn btn-success">
        </form>

        {% if resultado != None %}
            {% if resultado == True %}
                <p>A sequência <b>{{ sequencia }}</b> é aceite pelo regex </p>
            {% else %}
                <p>A sequência <b>{{ sequencia }}</b> não é aceite pelo regex </p>
            {% endif %}
        {% else %}
            <br><br>
        {% endif %}


    </main>

{% endblock %}


{% block aside %}
{% endblock %}

tc-django-master/computacao/templates/computacao/layout.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Teoría da Computação</title>

    {% load static %}
    <link rel="icon" type="image/png" href="{% static 'computacao/images/favicon.png' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <link rel="stylesheet" href="{% static 'computacao/style.css' %}">

</head>
<body>
    <header class="jumbotron text-center">
        <h1>Teoría da Computação</h1>
        <nav>
            <a href="{% url 'computacao:index' %}" class="btn btn-info" role="button">Introdução</a>
            <a href="{% url 'computacao:automatos' %}" class="btn btn-info" role="button">Autómatos</a>
            <a href="{% url 'computacao:maquinas' %}" class="btn btn-info" role="button">Máquinas de Turing</a>
            <a href="{% url 'computacao:expressoes' %}" class="btn btn-info" role="button">Expressões Regulares</a>            
        </nav>
    </header>
    <div  class="text-center">
         {% block main %}
        {% endblock %}
    </div>

</body>
</html>

tc-django-master/computacao/templates/computacao/maquina.html
{% extends 'computacao/layout.html' %}

{% block main %}


    <main class="col-sm-12">

        <h3>{{ maquina.nome|title }}</h3>

        <p>{{ maquina.descricao }}.</p>

        <table align="center">
            <tr align="left">
                <td>
                    <p> <b>Quíntuplo da máquina:</b></p>
                    <ul>
                    <li>Alfabeto: {{ maquina.printAlfabeto }} </li>
                    <li>Estados: {{ maquina.printEstados }}</li>
                    <li>Estado inicial: {{ maquina.estadoInicial }}</li>
                    <li>Estados aceitação: {{ maquina.printEstadosDeAceitacao }}</li>

                    <li>Tabela de transições:
                    <table align="center" rules="all" style="border-collapse: collapse">
                        {% for dTran in maquina.dTransInTable %}
                            <tr>
                                {% for element in dTran %}
                                    {% if forloop.parentloop.first %}
                                        <th>{{ element }}</th>
                                    {% elif forloop.first %}
                                        <th>{{ element }}</th>
                                    {% else %}
                                        <td>{{ element }}</td>
                                    {% endif %}
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </table>
                    </ul>
                </li>
                </td>
                <td class="align-baseline">

                    {% load static %}
                    <img src="{% static maquina.diagrama %}" alt="">
                    <p class="text-center">Diagrama de transições.</p>
                </td>
            </tr>
        </table>


        <br>
        <p><b>Validador:</b> Insira uma sequência e verifique se pertence à linguagem que a máquina reconhece: </p>
        <form action="{% url 'computacao:maquina' maquina.id %}" method="POST">
            {% csrf_token %}
           <b>{{ form }}</b>
            <input type="submit" value="validar" class="btn btn-success">
        </form>

        {% if resultado != None %}
            {% if resultado == True %}
                <p>A sequência <b>{{ sequencia }}</b> é aceite pela máquina </p>
            {% else %}
                <p>A sequência <b>{{ sequencia }}</b> não é aceite pela máquina </p>
            {% endif %}
        {% else %}
            <br><br>
        {% endif %}


    </main>

{% endblock %}


{% block aside %}
{% endblock %}

tc-django-master/computacao/templates/computacao/maquinas.html
{% extends 'computacao/layout.html' %}

{% block main %}

    <main class="col-sm-12 text-center">

        <h3>Máquinas de Turing</h3>
        <a href="{% url 'computacao:novamaquina' %}" class="btn btn-success btn-sm btn-block">
        Crie uma Máquina Turing
        </a>
        <br>
        <p>Apresentam-se em baixo as maquinás turing que foram criadas.</p>

        <table align="center" class="table" style="max-width:900px">
            <tr>
                <th class="text-center">Diagrama de Estados</th>
                <th class="text-center">Descrição</th>
            </tr>
            {% load static %}
            {% for maquina in maquinas %}
                <tr class="text-left">
                    <td>
                        <a href="{% url 'computacao:maquina' maquina.id %}">
                            <img src="{% static maquina.diagrama %}" alt="" width="80%">
                        </a>
                    </td>
                    <td style="vertical-align:bottom">
                        <p>{{ maquina.descricao }}</p>
                        <p>
                            <a href="{% url 'computacao:maquina' maquina.id %}" class="btn btn-info  btn-sm">
                                Detalhes
                            </a>
                            <a href="{% url 'computacao:maquina' maquina.id %}" class="btn btn-success  btn-sm">
                                Validar Sequência
                            </a>
                            <a href="{% url 'computacao:editamaquina' maquina.id %}" class="btn btn-warning  btn-sm">
                                Editar Máquina
                            </a>
                            <a href="{% url 'computacao:apagamaquina' maquina.id %}" class="btn btn-danger  btn-sm">
                                Apagar Máquina
                            </a>
                        </p>

                    </td>

                </tr>
            {% endfor %}
        </table>

    </main>

{% endblock %}

{% block aside %}
{% endblock %}

tc-django-master/computacao/templates/computacao/novaexpressao.html
{% extends 'computacao/layout.html' %}

{% block main %}
    <main class="col-sm-6">
        <h3>Regex</h3>
        <p>Pode aqui especificar uma nova expressão que ficará armazenada na base de dados.
            A expressão será implementada e poderá ser usada.</p>

        <form class="form-group" action="{% url 'computacao:novaexpressao' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="text-right">
                <a href="{% url 'computacao:expressoes' %}" role="button" class="btn btn-warning">Cancelar</a>
                <input type="submit" class="btn btn-success" value="submeter">
            </div>
        </form>
    </main>
    <aside class="col-sm-6 text-center">
        <br><br><br>
        {% load static %}

        <blockquote class="blockquote">
            <p class="mb-0"><img src="{% static 'computacao/images/turing-machine.png' %}" alt="">
                <br>
                Uma máquina pode fazer o trabalho de cinquenta homens comuns. Nenhuma máquina pode fazer o
                trabalho de um
                homem extraordinário.</p>
            <footer class="blockquote-footer">Elbert Hubbard</footer>
        </blockquote>
    </aside>
{% endblock %}

tc-django-master/computacao/templates/computacao/novamaquina.html
{% extends 'computacao/layout.html' %}

{% block main %}
    <main class="col-sm-6">
        <h3>Máquina Turing</h3>
        <p>Pode aqui especificar uma nova máquina que ficará armazenada na base de dados, juntamente com o seu diagrama.
            A máquina será implementada e poderá ser usada.</p>

        <form class="form-group" action="{% url 'computacao:novamaquina' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="text-right">
                <a href="{% url 'computacao:maquinas' %}" role="button" class="btn btn-warning">Cancelar</a>
                <input type="submit" class="btn btn-success" value="submeter">
            </div>
        </form>
    </main>
    <aside class="col-sm-6 text-center">
        <br><br><br>
        {% load static %}

        <blockquote class="blockquote">
            <p class="mb-0"><img src="{% static 'computacao/images/turing-machine.png' %}" alt="">
                <br>
                Uma máquina pode fazer o trabalho de cinquenta homens comuns. Nenhuma máquina pode fazer o
                trabalho de um
                homem extraordinário.</p>
            <footer class="blockquote-footer">Elbert Hubbard</footer>
        </blockquote>
    </aside>
{% endblock %}

tc-django-master/computacao/templates/computacao/novo_automato.html
{% extends 'computacao/layout.html' %}

{% block main %}
    <main class="col-sm-6">
        <h3>Autómato Finito Determinístico</h3>
        <p>Pode aqui especificar um novo autómato que ficará armazenado na base de dados, juntamente com o seu diagrama.
            O autómato será implementado e poderá ser usado.</p>

        <form class="form-group" action="{% url 'computacao:novo_automato' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="text-right">
                <a href="{% url 'computacao:automatos' %}" role="button" class="btn btn-warning">Cancelar</a>
                <input type="submit" class="btn btn-success" value="submeter">
            </div>
        </form>
    </main>
    <aside class="col-sm-6 text-center">
        <br><br><br>
        {% load static %}

        <blockquote class="blockquote">
            <p class="mb-0"><img src="{% static 'computacao/images/turing-machine.png' %}" alt="">
                <br>
                Uma máquina pode fazer o trabalho de cinquenta homens comuns. Nenhuma máquina pode fazer o
                trabalho de um
                homem extraordinário.</p>
            <footer class="blockquote-footer">Elbert Hubbard</footer>
        </blockquote>
    </aside>
{% endblock %}